version: 2

jobs:

  test:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.9.9
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
        environment:
          SRC_EMAIL_BACKEND: django.core.mail.backends.dummy.EmailBackend
          SRC_SECRET_KEY: stub
          SRC_USE_SENTRY: off
          SRC_DEBUG: off
          SRC_DATABASE_URL: postgresql://postgres:test_db_password@localhost/src_test_db
          SRC_CELERY_BROKER: redis://localhost:6379/1
          SRC_CELERY_TASK_ALWAYS_EAGER: on
      - image: postgres:14.1
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
        environment:
          POSTGRES_DB: src_test_db
          POSTGRES_PASSWORD: test_db_password
      - image: redis:6.2.6
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
    steps:
      - checkout
      - restore_cache:
          key: python-deps-v1-{{ checksum "requirements-dev.txt" }}
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv .env
            . .env/bin/activate
            pip install -U pip
            pip install -r requirements-dev.txt
      - save_cache:
          key: python-deps-v1-{{ checksum "requirements-dev.txt" }}
          paths:
            - ".env"
      - run:
          name: Check `black`
          command: . .env/bin/activate && black --check ./src
      - run:
          name: Check `isort`
          command: . .env/bin/activate && isort --check --skip .env ./src
      - run:
          name: Check `pylama`
          command: . .env/bin/activate && pylama ./src
      - run:
          name: Check `bandit`
          command: . .env/bin/activate && bandit -r --skip=B101 ./src
      - run:
          name: Check `safety`
          command: . .env/bin/activate && safety check
      - run:
          name: Check `pylint`
          command: . .env/bin/activate && pylint --django-settings-module=src.settings --ignore=tests src
      - run:
          name: Wait for Redis
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run:
          name: Wait for Postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Check for uncreated migrations
          command: |
            . .env/bin/activate
            python3 manage.py makemigrations --check --dry-run
      - run:
          name: Run tests
          command: |
            . .env/bin/activate
            python3 manage.py collectstatic --no-input
            pytest --cache-clear --capture=no --showlocals --verbose --cov=src --cov-report html --no-migrations --junitxml ./test-results/test-results.xml
      - store_test_results:
          path: ~/project/test-results

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
